### ISSUE TITLE
Allow solving for different platforms

### ISSUE THREAD

**Issue by habemus-papadum** [ESSS/conda-devenv#102]
Hi -- 
I currently use `anaconda-project` to maintain repeatable cross platform environments, but it has complexity that isn't really needed for my use case and I would like to consider alternatives such as `conda-devenv` -- in particular conditioning packages based on platform would be extremely useful.  

The one really useful thing about `anaconda-project` is that it knows how to solve environments for multiple platforms at once, independent of the host platform.  

If would be useful to be able to run `conda-devenv` in a mode in which is renders fully solved environment files for a given platform (which then would be checked into version control or just used to verify that the environments are actually solvable)

best, nehal

**Comment by nicoddemus** [comment]
Hi @habemus-papadum, 

You mean for `conda-devenv` to get a file like this:

```yaml
name: env
dependencies:
  - pip:
    - sphinx
  - gxx_linux-64=7.3.0  # [linux]
  - ccache              # [unix]
  - clcache             # [win]
```

And output a new `yaml` file with all dependencies and versions pinned, IOW, fully solved?
