### ISSUE TITLE
Improve docs about environment variables overriding

### ISSUE THREAD

**Issue by majidaldo** [ESSS/conda-devenv#112]
in the docs:
"
Environment variables defined as a single string (like DB_LOCATION above) will overwrite an existing variable with the same name.
"

in code:
```
   "Can't merge the key: '{key}' because it will override the previous value.",
                            "Only lists and dicts can be merged. The type obtained was: {type}",
```
https://github.com/ESSS/conda-devenv/blob/a0c0f7bc52a7e01cdb88bdeda39071c418f8b3da/conda_devenv/devenv.py#L219

**Comment by prusse-martin** [comment]
The error indicates that there are multiple definitions for that variable in different devenv files, not related to the exiting variables.
Maybe the error message and/or the docs should be improved.

Maybe we should add a flag to merge those as "use the first value (possible from the root devenv file)".
As a work around you could use jinga to omit that env var from the file when included (not the root devenv file) [using the `is_included` var](https://conda-devenv.readthedocs.io/en/latest/usage.html?highlight=is_included#jinja2):

```yaml
environment:
  {% if not is_included %}
  DB_LOCATION: https://localhost/dev
  {% endif %}
```

**Comment by edisongustavo** [comment]
> Maybe we should add a flag to merge those as "use the first value (possible from the root devenv file)".

I would be opposed to doing that. You can easily end up in a situation where you don't know why an environment variable has a given value. And that will be long hours debugging something.

**Comment by nicoddemus** [comment]
Agreed, better to raise an error, we just need to update the docs I think.

**Comment by majidaldo** [comment]
> The error indicates that there are multiple definitions for that variable in different devenv files, not related to the exiting variables.
> Maybe the error message and/or the docs should be improved.
> 
> Maybe we should add a flag to merge those as "use the first value (possible from the root devenv file)".
> As a work around you could use jinga to omit that env var from the file when included (not the root devenv file) [using the `is_included` var](https://conda-devenv.readthedocs.io/en/latest/usage.html?highlight=is_included#jinja2):
> 
> ```yaml
> environment:
>   {% if not is_included %}
>   DB_LOCATION: https://localhost/dev
>   {% endif %}
> ```
> 
> We did opt for the "merge error" to avoid variables defined in some devenv file to be silently ignored.

 Yup. That's what I did. For data sciency work, I claim the following template is everything that you need.
```
# copy/paste into your work dir
#                           add more work dirs if needed
{% set included_workdirs = ['project', ] %}
{% set run_req = not is_included %}

dependencies: []
    #- sometestframework            
    #- some analysis library     # [run_req]
environment:
  # probably want to append PATH and PYTHONPATH in your env
  PATH:
    - '{{ os.path.join(root, "wbin") }}'
    - '{{root}}'
  PYTHONPATH:
    - '{{root}}'
  # don't define the following in envs that include this
  WORK_DIR: '{{  os.path.basename(root) }}'                       # [not is_included]
  WORKDIR:  '{{  os.path.basename(root) }}'                       # [not is_included]
  WORK_DIR_PATH: '{{root}}'                                       # [not is_included]
  WORKDIR_PATH:  '{{root}}'                                       # [not is_included]
  PROJECTROOT:  '{{ os.path.abspath(os.path.join(root, '..')) }}' # [not is_included]
  PROJECT_ROOT: '{{ os.path.abspath(os.path.join(root, '..')) }}' # [not is_included]
includes:
{% for included in included_workdirs %}
  - '{{root}}/../{{included}}/environment.devenv.yml'
{% endfor %}
name: {{'mydatascienceproject-' + os.path.basename(root)}}

```
