### ISSUE TITLE
Proposal: pins/run_constrained support

### ISSUE THREAD

**Issue by nicoddemus** [ESSS/conda-devenv#145]
## Problem

To ensure all projects use the same "blessed" versions, we use a strategy where we include other `devenv.yml` files which exist solely to specify package versions, for example:

```yaml
name: app
includes:
   - {{ eden }}/environment.devenv.yml
   - {{ eden }}/pytest.devenv.yml
dependencies:
   - cogapp ==0.3
```

With the other files being:

```yaml
# eden/environment.devenv.yml
name: eden
dependencies:
  - artifacts_cache ==3.0.0
  - attrs ==21.2.0
  - black ==21.12b0
environment:
  - PYTHONPATH: {{ root }}/source/python
```

```yaml
# eden/pytest.devenv.yml
dependencies:
  - pytest ==6.2.5
  - pytest-mock ==3.0.0
  - pytest-lazy-fixture ==0.6.0
```

The purpose here is to make sure we are using the same versions, without putting all dependencies in `eden/environment.devenv.yml`, as that would bloat all environments that include it.

This works, but it has some problems:

* Versions are scattered in many `devenv.yml` files, which makes it difficult to update versions as often there are conflicts, and we need to hunt down the offending pins.
* Often, for brevity and avoiding having an explosion of `devenv.yml` files, we put a lot of packages in the same file because they are often related, but that's not always true or convenient. For example, when we include `pytest.devenv.yml` above, we will get `pytest-lazy-fixture` whether we use it or not.

## Proposal

We add a new section in the `devenv.yml` files, named `pins`. This contains a number of packages and pins (mandatory), which will be used when processing the `dependencies` of the chain of `devenv.yml` files. Any dependency in `devenv` files which has a pin in the `pins` section, will be pinned accordingly in the final `environment.yml` file generated.

For example, we can have pins directly into `eden/environment.devenv.yml`, which is included by all other projects:

```yaml
name: eden
pins:
  - artifacts_cache ==3.0.0
  - attrs ==21.2.0
  - black ==21.12b0
  - cogapp ==0.3
  - pytest ==6.2.5
  - pytest-mock ==3.0.0
  - pytest-lazy-fixture ==0.6.0
dependencies:
  - artifacts_cache
  - attrs
  - black
```

`pins` doesn't mean that dependency will be included, but if any of the `dependencies` include a package in `pins` which is not itself pinned, then it will be pinned accordingly.

```yaml
name: app
includes:
   - {{ eden }}/environment.devenv.yml   
dependencies:
   - cogapp
   - pytest
```

Having a pin file, all `dependencies` sections in `devenv.yml` files can now leave things unpinned, with the pin being managed by the `pins` section.

### Dependencies with pins

If a `dependencies` section specifies a pinned package, then the generated file will contain both pins:

```yaml
name: eden
pins:
  - artifacts_cache ==3.0.0
```

```yaml
name: app
includes:
   - {{ eden }}/environment.devenv.yml   
dependencies:
   - artifacts_cache >=2.4.0
```

In this example the generated `environment.yml` will contain the entry `artifacts_cache: >=2.4.0, ==3.0.0`, which conda will be able to solve. If they conflict for, conda will fail as expected.

### Multiple `pins`

It is possible to have multiple `pins` sections in a chain of `devenv.yml` files, we should error out if different `pin` sections try to pin the same library (this from the POV of `conda-devenv`, we probably should have a single `pins` section in one file).

### Usage in `eden`

We probably will have a separate `pins.devenv.yml` file, to avoid polluting `eden/environment.devenv`:

```yaml
# eden/pins.devenv.yml
pins:
  - artifacts_cache ==3.0.0
  - attrs ==21.2.0
  - black ==21.12b0
  - cogapp ==0.3
  - pytest ==6.2.5
  - pytest-mock ==3.0.0
  - pytest-lazy-fixture ==0.6.0
```

```yaml
name: eden
includes:
  - {{ root }}/pins.devenv.yml
dependencies:
  - artifacts_cache
  - attrs
  - black
```

### What about "lock files"  

Locking is a different use case/concern, and does not conflict with this proposal.

(note: much of the ideas and solutions here were result from discussions with @tadeu)

**Comment by prusse-martin** [comment]
As I understand this will not affect transitive dependencies.
We could document this behavior but I think it a bit strange.
Say we have:
```yml
name: foo
pins:
  - pytest ==6.2.5
  - pytest-mock ==3.0.0
  - pytest-lazy-fixture ==0.6.0
dependencies:
  - pytest-lazy-fixture
```
As I see it will respect `pytest-lazy-fixture ==0.6.0` but not `pytest ==6.2.5` (and pytest is a dependency of pytest-lazy-fixture).
