### ISSUE TITLE
inconsistent 'schema' when merging with  non-pip

### ISSUE THREAD

**Issue by majidaldo** [ESSS/conda-devenv#154]
```
name: d1
dependencies:
  - d11
  - d12
  - pip
  - other:
    - o11
    - o12
  - other2:
    - o12
  - pip:
    - p12
```
```
name: d2
includes:
  - d1.devenv.yml
dependencies:
  - d11
  - d21
  - d22
  - pip
  - pip:
    - p21
```
gives:
```
(base) λ conda devenv --file d2.devenv.yml  --print-full
# generated by conda-devenv, do not modify and do not commit to VCS
dependencies:
- d11
- d12
- d21
- d22
- pip
- other:
  - o11
  - o12
  other2:
  - o12
  pip:
  - p12
  - p21
name: d2
environment: {}
```
if you just have pip, you get the expected.
```
dependencies:
- d11
- d12
- d21
- d22
- pip
- pip:
  - p12
  - p21
name: d2
```
related: https://github.com/ESSS/conda-devenv/issues/152
