### ISSUE TITLE
conda-lock --update stripping auth environment variables

### ISSUE THREAD

**Issue by nicoddemus** [ESSS/conda-devenv#174]
Hi folks!

First of all thanks for the amazing tool!

At work we are using private channels with an embeded token via an environment variable. 

When we create the lock file the first time, it correctly embeds the token environment variable in each package URL. However, when we call `--update`, it strips the authentication token from all URLs.

Is this a bug or are we using `conda-lock` incorrectly?

---

Reproducer:

```yaml
name: test
channels:
  - https://${ESSS_CONDA_CHANNEL_TOKEN}@eden.esss.co/conda-channel/mirror-conda-forge  
platforms:
  - linux-64
  - win-64
dependencies:
  - boltons
```

```console
$ mamba lock
```

This generates the `conda-lock.yml` file correctly, with each URL containing the environment variable embeded:

```yaml
version: 1
metadata:
  content_hash:
    linux-64: 346581838184a77a7ad753d826aa2344e261e15be2579084a81781b2d33255b5
    win-64: e74885d79ac8882146d215d23539fb52c968c24dff91bd8dcee2d4e68b0754d1
  channels:
  - url: https://$ESSS_CONDA_CHANNEL_TOKEN@eden.esss.co/conda-channel/mirror-conda-forge
    used_env_vars:
    - ESSS_CONDA_CHANNEL_TOKEN
  platforms:
  - linux-64
  - win-64
  sources:
  - environment.yml
package:
- name: boltons
  version: 23.0.0
  manager: conda
  platform: linux-64
  dependencies:
    python: =2.7|>=3.7
  url: https://$ESSS_CONDA_CHANNEL_TOKEN@eden.esss.co/conda-channel/mirror-conda-forge/noarch/boltons-23.0.0-pyhd8ed1ab_0.conda
  hash:
    md5: 033eb25fffd222aceeca6d58cd953680
    sha256: 4ff828cceb8f55cb26d23b1a4c174d22c7cd92350221724bcaf2d6632e33fdee
  category: main
  optional: false
```

Note the `url: https://$ESSS_CONDA_CHANNEL_TOKEN@eden.esss.co/conda-channel/mirror-conda-forge/noarch/` line.

However when we execute:

```console
$ mamba lock --update boltons
```

All the `$ESSS_CONDA_CHANNEL_TOKEN` strings are being stripped:

```yaml
version: 1
metadata:
  content_hash:
    linux-64: 346581838184a77a7ad753d826aa2344e261e15be2579084a81781b2d33255b5
    win-64: e74885d79ac8882146d215d23539fb52c968c24dff91bd8dcee2d4e68b0754d1
  channels:
  - url: https://$ESSS_CONDA_CHANNEL_TOKEN@eden.esss.co/conda-channel/mirror-conda-forge
    used_env_vars:
    - ESSS_CONDA_CHANNEL_TOKEN
  platforms:
  - linux-64
  - win-64
  sources:
  - environment.yml
package:
- name: boltons
  version: 23.0.0
  manager: conda
  platform: linux-64
  dependencies:
    python: =2.7|>=3.7
  url: https://eden.esss.co/conda-channel/mirror-conda-forge/noarch/boltons-23.0.0-pyhd8ed1ab_0.tar.bz2
  hash:
    md5: 033eb25fffd222aceeca6d58cd953680
    sha256: 4ff828cceb8f55cb26d23b1a4c174d22c7cd92350221724bcaf2d6632e33fdee
  category: main
  optional: false
```

Note the `url: https://eden.esss.co/conda-channel/mirror-conda-forge/noarch/boltons-23.0.0-pyhd8ed1ab_0.tar.bz2` line.
