### ISSUE TITLE
Support for constrained/optional dependencies

### ISSUE THREAD

**Issue by nicoddemus** [ESSS/conda-devenv#180]
# Problem

In dependent repositories, it is common that a core/base repository only works with some specific versions of a library, for example:

* A repository of common utilities contains tasks that only work with `vtk >9` or `alive-progress < 2`.
* Some framework code requires a specific version of another library, for example `Qt =5.12` or `pytest >7`.

The problem here is that those repositories do not really depend on those packages, because they are actually *optional* -- for example, one can use the common repository but not depend on `vtk`. For this reason the common repository cannot declare the dependency directly, otherwise all downstream `devenv.yml` files will inherit that dependency.

One of the solutions we have used so far is to have independent `.devenv.yml` files (for example `vtk.devenv.yml`, `pytest.devenv.yml`, etc) which the downstream `.devenv.yml` files *include*, as opposed to the common/upstream `devenv.yml` declaring the dependencies themselves. This solves the problem, but is a bit clunky:

* We need a bunch of those optional `devenv.yml` files in the upstream repositories (often all bunched up in a single repository, even if that repository does not care about those packages).
* Error prone: if an upstream repository now needs to restrict a package, we need to include a `pkg.devenv.yml` file and manually go to all dependent repositories that are affected and make them *include* the new `pkg.devenv.yml` file.

# Proposal

[Conda](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run-constrained) and [pip](https://pip.pypa.io/en/stable/user_guide/#constraints-files) have the concept of *constraints*, which are package version restrictions that do not cause a package to be included in the environment directly, but if they are included in the environment by other means, then they must respect the pins.

The proposal is for `devenv.yml` files to also support those constraint pins:

```yml
name: common-utils
dependencies:
- boltons
- attrs
contraints:
- pytest >7
```

Running `conda devenv` in this file will install `['boltons', 'attrs']`, but not `pytest`.

Consider this downstream `devenv.yml` file:

```yml
name: app
includes:
- {{ root }}/../common-utils/environment.devenv.yml
dependencies:
- pyqt
```

It includes `common-utils/environment.devenv.yml`, but does not declare `pytest` as a direct dependency, so running `conda devenv` will install `['boltons', 'attrs', 'pyqt']`.

Consider another downstream `devenv.yml` file:

```yml
name: app2
includes:
- {{ root }}/../common-utils/environment.devenv.yml
dependencies:
- pyqt
- pytest
```

In this case, the *constrained* pytest version is directly declared, so the constraint will be respected and `['boltons', 'attrs', 'pyqt', 'pytest >7']` will be installed.

## Semantics

The *constraint* section will only be considered when processing *included* `devenv.yml` files, IOW, those which appear in `included:` sections of the `devenv.yml` file which was passed to `conda devenv` directly (recursively).

As a practical example:

```yml
name: common-utils
dependencies:
- attrs >19
contraints:
- pytest >7
- ftputil >3
```

```yml
name: common-core
includes:
- {{ root }}/../common-utils/environment.devenv.yml
dependencies:
- boltons
contraints:
- requests >2
- diff-cover >4
```

```yml
name: app
includes:
- {{ root }}/../common-core/environment.devenv.yml
dependencies:
- pyqt
- requests
- pytest
```

1. In the first pass, we process the `dependencies` sections and obtain: `['attrs >19', 'boltons', 'pyqt', 'pytest', 'requests']`.
2. Now we process the `contraints` sections: for each package in `constraints` that we also have in `dependencies`, we include the contraints in the `dependencies`, which results in `['attrs >19', 'boltons', 'pyqt', 'pytest', 'pytest >7', 'requests', 'requests >2']`, generating:

   ```yml
   name: app
   dependencies:
   - attrs > 19
   - boltons 
   - pyqt
   - pytest, pytest >7
   - requests, requests >2
   ```
3. If the direct `devenv.yml` file (here `app`) contains a `constraints` section, it is ignored. We will not issue a warning because it is possible for a file to be used directly and also be included, with constraints, so we do not want to generate noise.
