### ISSUE TITLE
Question: Is it possible to load environment variables from an dotenv file?

### ISSUE THREAD

**Issue by paoslaos** [ESSS/conda-devenv#195]
The readme on the main page is quite nice and helps in using environment variables. Is there a way to use variables that are defined via a [python-dotenv file](https://pypi.org/project/python-dotenv/)?

```yaml
# don't use os but a dot env?
{% set conda_py = os.environ.get('CONDA_PY', '35') %}
name: web-ui-py{{ conda_py }}

includes:
  - {{ root }}/../core-business/environment.devenv.yml

```

The dotenv is just a file that looks like this:

```env

# Development settings
CONDA_PY='35'
```
