### ISSUE TITLE
Issues with pip hg dependencies.

### ISSUE THREAD

**Issue by mforbes** [ESSS/conda-devenv#91]
The following pip dependency section gets mangled:

```yml
# environment.devenv.yml
name: test
dependencies:
  - pip
  - pip:
    - hg+ssh://hg@bitbucket.org/mforbes/mmfutils-fork@0.4.12
    - hg+ssh://hg@bitbucket.org/mforbes/pytimeode@0.9
```

```bash
conda devenv --print
# generated by conda-devenv, do not modify and do not commit to VCS
dependencies:
- pip
- pip:
  - hg +ssh://hg@bitbucket.org/mforbes/mmfutils-fork@0.4.12,+ssh://hg@bitbucket.org/mforbes/pytimeode@0.9
name: test
```
Note that a space gets inserted in "hg +ssh" and the two lines are concatenated.  Both effects break the subsequent conda install with a message:

```bash
Invalid requirement: 'hg +ssh://hg@bitbucket.org/mforbes/mmfutils-fork@0.4.12,+ssh://hg@bitbucket.org/mforbes/pytimeode@0.9'
It looks like a path. File 'hg +ssh://hg@bitbucket.org/mforbes/mmfutils-fork@0.4.12,+ssh://hg@bitbucket.org/mforbes/pytimeode@0.9' does not exist.

```
